sysbuild: option system

diff --git a/.config/system/sysbuild b/.config/system/sysbuild
--- a/.config/system/sysbuild
+++ b/.config/system/sysbuild
@@ -4,6 +4,7 @@ set -e
 scriptdir="$(dirname "$0")"
 pkgdir="$scriptdir"/packages
 servicedir="$scriptdir"/services
+optdir="$scriptdir"/options
 
 [ "$(id -u)" -ne 0 ] && echo "error: run as root" && return 1
 
@@ -18,6 +19,9 @@ conf="$1"
     [ ! -d "$servicedir" ] && echo "error: no directory '$servicedir'" 
     [ ! -f "$servicedir"/common ] && echo "error: no file '$servicedir/common'" 
     [ ! -f "$servicedir"/"$conf" ] && echo "error: no file '$servicedir/$conf'" 
+    [ ! -d "$optdir" ] && echo "error: no directory '$optdir'" 
+    [ ! -f "$optdir"/common ] && echo "error: no file '$optdir/common'" 
+    [ ! -f "$optdir"/"$conf" ] && echo "error: no file '$optdir/$conf'" 
 } && return 1
 
 of () {
@@ -31,19 +35,68 @@ of "$pkgdir"/common >> /etc/apk/world
 of "$pkgdir"/"$conf" >> /etc/apk/world
 chmod -w /etc/apk/world
 
-apk fix
+apk fix --upgrade
 
 diff -U 0 /etc/apk/world.last /etc/apk/world
 
-service_add="$(mktemp)"
-service_del="$(mktemp)"
+service_fix () {
+    of "$1" | while IFS= read -r line; do
+        runlevel="$(echo "$line" | cut -d ':' -f 1)"
+        action="$(echo "$line" | cut -d ':' -f 2)"
+        service="$(echo "$line" | cut -d ':' -f 3)"
+        rc-update "$action" "$service" "$runlevel"
+    done
+}
 
-of "$servicedir"/common | grep "^+" | tr -d '+' >> "$service_add"
-of "$servicedir"/common | grep "^-" | tr -d '-' >> "$service_del"
+set +e
+service_fix "$servicedir/common"
+service_fix "$servicedir"/"$conf"
+set -e
 
-xargs -I {} rc-update add {} < "$service_add"
-xargs -I {} rc-update del {} < "$service_del"
+put_opt () {
+    grep -qx "^[[:space:]]*$1[[:space:]]*\$" "$2" && return
+    echo "$1" >> "$2"
+}
 
-rm "$service_add" "$service_del"
+set_opt () {
+    tmpfile="$(mktemp)"
+    cat "$3" | sed "s/^[[:space:]]*\($1\).*\$/\1$2/" > "$tmpfile"
+    mv "$tmpfile" "$3"
+}
+
+sed_opt () {
+    grep -qx "$1" "$3" && return 0
+    tmpfile="$(mktemp)"
+    sed "$2" "$3" > "$tmpfile"
+    cmp -s "$3" "$tmpfile"
+    exit_status="$?"
+    mv "$tmpfile" "$3"
+    return "$exit_status"
+}
+
+option_fix () {
+    of "$1" | while IFS= read -r line; do
+        file="$(echo "$line" | cut -d ':' -f 1)"
+        action="$(echo "$line" | cut -d ':' -f 2)"
+
+        if [ "$action" = "put" ]; then
+            s1="$(echo "$line" | cut -d ':' -f 3)"
+            put_opt "$s1" "$file"
+        elif [ "$action" = "set" ]; then
+            s1="$(echo "$line" | cut -d ':' -f 3)"
+            s2="$(echo "$line" | cut -d ':' -f 4)"
+            set_opt "$s1" "$s2" "$file"
+        elif [ "$action" = "sed" ]; then
+            togrep="$(echo "$line" | awk -F '  ' '{print $2}')"
+            tosed="$(echo "$line" | awk -F '  ' '{print $3}')"
+            sed_opt "$togrep" "$tosed" "$file" || {
+                echo "$line" | awk -F '  ' '{print $NF}' | sh
+            }
+        fi
+    done
+}
+
+option_fix "$optdir"/common
+option_fix "$optdir"/"$conf"
 
 echo "Done!"
